// One-time admin script: seeds the local `users` table on DigitalOcean
// Postgres with the app's accounts. Fully self-contained — no Supabase
// dependency of any kind (ids are freshly generated by the DB default).
//
// Usage: bun run scripts/seed-users.ts researcher@example.com supervisor@example.com
// Safe to re-run: an email that's already seeded is skipped.

import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { db } from "../src/db.server";
import { hashPassword } from "../src/passwordHash.server";

async function main() {
  const emails = process.argv.slice(2);
  if (emails.length === 0) {
    console.error("Usage: bun run scripts/seed-users.ts <email1> [email2] ...");
    process.exit(1);
  }

  const rl = createInterface({ input: stdin, output: stdout });

  try {
    for (const email of emails) {
      const existing = await db.query("SELECT id FROM users WHERE email = $1", [email]);
      if (existing.rows.length > 0) {
        console.log(`- ${email}: already seeded, skipping`);
        continue;
      }

      console.log(`\n${email}`);
      let role = "";
      while (role !== "researcher" && role !== "supervisor") {
        role = (await rl.question("  role (researcher/supervisor): ")).trim();
      }
      const password = await rl.question("  password: ");
      if (!password) {
        console.error(`✗ ${email}: empty password, skipping`);
        continue;
      }

      const passwordHash = await hashPassword(password);
      const { rows } = await db.query(
        `INSERT INTO users (email, password_hash, role, token_version)
         VALUES ($1, $2, $3, 1) RETURNING id`,
        [email, passwordHash, role],
      );
      console.log(`✓ ${email}: seeded as ${role} (id=${rows[0].id})`);
    }
  } finally {
    rl.close();
    await db.end();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
