import React, { useEffect, useState, useCallback, useRef } from "react";
import { loadNotifications, markAllNotificationsRead } from "./cloudSync";

// A compact bell button that shows a red badge with the count of unread
// supervisor-room activity generated by other users. Clicking the bell
// opens a dropdown with the list; clicking an item navigates to the
// supervisor room (and marks everything read).
export default function NotificationBell({ onOpenSupervisor }) {
  const [count, setCount] = useState(0);
  const [items, setItems] = useState([]);
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const rootRef = useRef(null);

  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      const { count: c, items: i } = await loadNotifications({ limit: 15 });
      setCount(c);
      setItems(i);
    } catch (e) {
      console.warn("[NotificationBell.refresh]", e);
    } finally {
      setLoading(false);
    }
  }, []);

  // Refresh on mount + every 60s (matches user's "refresh on load" preference —
  // no realtime, just periodic polling while the tab is open).
  useEffect(() => {
    refresh();
    const t = setInterval(refresh, 60000);
    return () => clearInterval(t);
  }, [refresh]);

  // Close the dropdown when clicking outside
  useEffect(() => {
    if (!open) return;
    const handler = (e) => {
      if (rootRef.current && !rootRef.current.contains(e.target)) setOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  const openItem = async (it) => {
    setOpen(false);
    await markAllNotificationsRead();
    setCount(0);
    setItems([]);
    if (onOpenSupervisor) onOpenSupervisor(it.tab);
  };

  const markRead = async () => {
    await markAllNotificationsRead();
    setCount(0);
    setItems([]);
  };

  return (
    <div ref={rootRef} style={{ position: "relative", display: "inline-block" }} data-testid="notification-bell-root">
      <button
        onClick={() => setOpen(o => !o)}
        title={count > 0 ? `${count} إشعار جديد من المشرف` : "لا توجد إشعارات جديدة"}
        data-testid="notification-bell-btn"
        style={{
          background: count > 0 ? "rgba(251,191,36,0.95)" : "rgba(255,255,255,0.15)",
          border: "1px solid rgba(255,255,255,0.3)",
          color: count > 0 ? "#1e293b" : "white",
          padding: "5px 9px",
          borderRadius: 6,
          cursor: "pointer",
          fontSize: 13,
          fontFamily: "inherit",
          fontWeight: 700,
          display: "flex",
          alignItems: "center",
          gap: 4,
          position: "relative",
          transition: "background 0.2s ease",
        }}
      >
        <span style={{ fontSize: 14 }}>🔔</span>
        {count > 0 && (
          <span
            data-testid="notification-bell-count"
            style={{
              background: "#dc2626",
              color: "white",
              borderRadius: 999,
              padding: "1px 6px",
              fontSize: 10,
              minWidth: 18,
              display: "inline-flex",
              alignItems: "center",
              justifyContent: "center",
              lineHeight: 1.3,
            }}
          >
            {count > 99 ? "99+" : count}
          </span>
        )}
      </button>

      {open && (
        <div
          data-testid="notification-bell-dropdown"
          dir="rtl"
          style={{
            position: "absolute",
            top: "calc(100% + 6px)",
            left: 0,
            width: 340,
            maxHeight: 420,
            overflowY: "auto",
            background: "white",
            color: "#1e293b",
            borderRadius: 10,
            boxShadow: "0 20px 40px rgba(0,0,0,0.25)",
            border: "1px solid #e2e8f0",
            zIndex: 1000,
            fontFamily: "inherit",
          }}
        >
          <div style={{ padding: "10px 14px", borderBottom: "1px solid #f1f5f9", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <div style={{ fontWeight: 700, fontSize: 13 }}>
              📬 صندوق الإشعارات
              {count > 0 && <span style={{ marginRight: 6, color: "#dc2626", fontSize: 12 }}>({count})</span>}
            </div>
            {count > 0 && (
              <button
                onClick={markRead}
                data-testid="notification-mark-all-read"
                style={{ background: "transparent", border: "1px solid #e2e8f0", color: "#64748b", padding: "3px 8px", borderRadius: 5, cursor: "pointer", fontSize: 10, fontFamily: "inherit" }}
              >
                تعليم الكل مقروء
              </button>
            )}
          </div>

          {loading && <div style={{ padding: 16, textAlign: "center", color: "#94a3b8", fontSize: 12 }}>جاري التحميل…</div>}
          {!loading && items.length === 0 && (
            <div style={{ padding: 24, textAlign: "center", color: "#94a3b8", fontSize: 12 }} data-testid="notification-empty">
              ✅ لا توجد إشعارات جديدة
              <div style={{ fontSize: 10, marginTop: 4, opacity: 0.8 }}>ستظهر هنا كل ملاحظة أو سؤال يرسله المشرف</div>
            </div>
          )}
          {!loading && items.map((it, idx) => (
            <button
              key={`${it.table}-${it.id}-${idx}`}
              onClick={() => openItem(it)}
              data-testid="notification-item"
              style={{
                display: "block",
                width: "100%",
                textAlign: "right",
                background: "transparent",
                border: "none",
                borderBottom: "1px solid #f8fafc",
                padding: "10px 14px",
                cursor: "pointer",
                fontFamily: "inherit",
                fontSize: 12,
              }}
              onMouseEnter={e => (e.currentTarget.style.background = "#f8fafc")}
              onMouseLeave={e => (e.currentTarget.style.background = "transparent")}
            >
              <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 3 }}>
                <span style={{ fontSize: 14 }}>{it.icon}</span>
                <span style={{ fontWeight: 700, color: "#1e3a5f" }}>{it.label}</span>
                {it.chapter && (
                  <span style={{ background: "#eff6ff", color: "#3B82F6", padding: "1px 6px", borderRadius: 4, fontSize: 10 }}>
                    {it.chapter}
                  </span>
                )}
              </div>
              <div style={{ color: "#334155", lineHeight: 1.6, overflow: "hidden", display: "-webkit-box", WebkitBoxOrient: "vertical", WebkitLineClamp: 2, textOverflow: "ellipsis" }}>
                {it.title}
              </div>
              {it.date && (
                <div style={{ color: "#94a3b8", fontSize: 10, marginTop: 3 }}>📅 {it.date}</div>
              )}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
